#!/usr/bin/env bash
# myShellEnv v 1.0 [aeondigital.com.br]


MSE_MD_PROMPT_SELECTED_STYLE_NAME="NEWLINE_MINIMAL"
MSE_MD_PROMPT_SELECTED_PH_COLOR[PROMPT_SIGN]="4 BOLD NONE LBLUE"
MSE_MD_PROMPT_SELECTED_PH_COLOR[USERNAME]="4 NONE NONE DWHITE"
MSE_MD_PROMPT_SELECTED_PH_COLOR[AT_SIGN]="4 NONE NONE LBLUE"
MSE_MD_PROMPT_SELECTED_PH_COLOR[HOSTNAME_SHORT]="4 NONE NONE DWHITE"
MSE_MD_PROMPT_SELECTED_PH_COLOR[ZCOLOR_01]="4 NONE NONE LBLUE"
MSE_MD_PROMPT_SELECTED_PH_COLOR[DIRECTORY_PATH]="4 NONE NONE DWHITE"
